index.html

„im Klaren... “ Klaren wird großgeschrieben. Quelle: http://www.duden.de/sprachwissen/sprachratgeber/beispiele-zur-neuen-rechtschreibung

Correct spelling mistake

---

app.js

Support versions that include an additional alphanumeric string prefixed with a plus like the following examples.
- 2016.2.2+mwu1
- 2016.2+mwu~exp2016120501
I tested the new regex with the conventional version schema and the new one and I didn't see any problems.

Support different version schema

---

devices.js

The filename for the _Ubiquiti⁣ UniFi AP Outdoor+_ can also be encoded with a lowercase 'b'.

Added another way to write 'Ubiquiti⁣ UniFi AP Outdoor+⁣' to devices.js

---

devices.js

This PR adds support for the Xiaomi MiWiFi Mini to the `devices.js`.

Add support for Xiaomi MiWiFi Mini

---

app.js
config_template.js
devices.js

This introduces the possibility to split the device list into categories.
We use this to roughly split devices by their hardware specifications.
Displayed categories are defined in the config.js file. Default behavior is to exclude devices with less than 64MB RAM or 4MB flash-memory.

Introduce device categories

---

app.js
devices.js

This fixes the handling of device names containing regex special chars by escaping all of them acording to `escapeRegExp` from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions.
A running instance of this can be found here: https://firmware.fulda.freifunk.net/selector/

Escape regex in device name the right way

---

app.css

Currently, the firmware wizard displays a different number of models in each row of the preview-area, depending on the images dimensions or model name length.
This commit changes the properties to display a fixed number of models per row, based on the width of the browsers window.

change preview layout to css-grid

---

devices.js

The company doesn't seem to be called "GL Innovations", at least nowadays.
On their website, you find a reference to "GL Technologies &
Microuter Technologies", but devices are all referred as GL.iNet GL-XXX,
so we should use this name instead.
Adjust naming of the devices accordingly.

rename GL Innovations to GL.iNet

---

app.css

The `background-color` of `<body>` is grey on Firefox. This commit sets it to `white`.

set background-color to white

---

app.css
app.js
config_template.js
index.html

Branch names may differ between communities but the names, descriptions and which one is recommended is hardcoded in the _index.html_ file. This patch makes them configurable.
A string for each branch that is defined in `directories` can be set via `branch_descriptions` and is looked up during the selection process. In addition you can decide which branch is marked as recommended by setting `recommended_branch`.
```
...
directories: {
// some demo sources
'./images/gluon-factory-example.html': 'stable',
'./images/gluon-sysupgrade-example.html': 'stable'
},
// branch descriptions shown during selection
branch_descriptions: {
stable: 'Gut getestet, zuverlässig und stabil.',
beta: 'Vorabtests neuer Stable-Kandidaten.',
experimental: 'Ungetestet, automatisch generiert.'
},
// recommended …
```

make branch descriptions configurable

---

devices.js

There is no WT3020 8M model. It is just the unified image for WT3020AD/F/H.

ignore nexx-wt3020-8m image

---

devices.js

Image name changed in https://github.com/freifunk-gluon/gluon/commit/ce8cf1b9006f3571cd94fd3f437d4535d4f863c8

update TP-Link TL-WR841N/ND v13 image name

---

app.js

Revisions of one device might have different available images.
For example only v3 of the TP-Link Archer C50 has a bootloader image.
But without filtering a button "Bootloader-Image" would also be shown
for the v4 (and all future revisions).
Version with applied fix:
v3: https://wizard.freifunk-mwu.de/?q=TP-Link%E2%81%A3%20Archer%C2%A0C50%E2%81%A3%20v3%E2%81%A3
v4: https://wizard.freifunk-mwu.de/?q=TP-Link%E2%81%A3%20Archer%C2%A0C50%E2%81%A3%20v4%E2%81%A3

Include revision in getImageTypes() filter

---

app.js

reFileExtension had a problem caused false replacing of extensions 
(for examble extension "ubi" replaced ubi in ubiquity and left extension "bin")
e.g. file:
gluon-comm-0.1.2-stable.0-20190722-ubiquiti-unifi-ac-mesh-sysupgrade.bin
would have been (wrong):
quiti-unifi-ac-mesh-.bin.jpg
instead of (correct): 
ubiquiti-unifi-ac-mesh.jpg
should fix (at least parts) of #92 
not sure if the first dot in line 123 should also be escaped
RegExp(/.(bin|img\\.gz|img|tar|ubi)$/);
RegExp(/\\.(bin|img\\.gz|img|tar|ubi)$/);

fix RegExp FileExtension

---

app.js
config_template.js

one commit removes a source code comment as the text of the comment would only apply to the example config (ffda version scheme)
2nd commit replaces the regex used for version detection with a "real" regex instead of a string.

two small improvements around regex

---

app.css
app.js
config_template.js
devices.js
index.html

I added an array of links to for devices with which need special flash instructions.
It is rather simple and tries to find an entry in a list called `devices_info` in _devices.js_.
```
var devices_info = {
"AVM": {
"FRITZ!Box 4020": "https://fritzfla.sh",
...
}
...
}
```
A community can also overwrite the defined links via a `devices_info` list in their _config.js_
```
var config = {
....
// links for instructions like flashing of certain devices (optional)
// overwrites values from devices_info in devices.js
devices_info: {
'AVM': {
"FRITZ!Box 4040": "https://fritz-tools.readthedocs.io"
}
}
};
```
**example**
The text is just a first example and suggestions are welcome ;-)
Should Fix #95

Add list for flash instructions

---

devices.js

Der Name des `FRITZ!Repeater 1200` stimmt in den Installatonsanweisungen nicht. Dadurch funktioniert das Anzeigen des Anleitungs-Links nicht. Dies sollte das beheben.
Damit ist er auch identisch zu der Zeile 
https://github.com/freifunk-darmstadt/gluon-firmware-selector/blob/2e857f83d08c0d24ec8a6dd5e20708693447d74d/devices.js#L37
in der Definition für das Firmware Image.

devices: fix name of FRITZ!Repeater 1200

---

app.js

When testing #109 I noticed that the checkbox for not recommended devices was kept checked during a page reload but the corresponding devices were not shown. This patch unckecks the checkbox during page load.

app: always uncheck "not recommended" checkbox

---

app.js
index.html

This commit adds bootloader images to the column "Erstinstallation" in the table view. As devices with bootloader images should not have factory images I don't see a need to add an extra column which is empty for almost all devices.
Fixes #91

app: add bootloader images to table view

---

devices.js

Due to the known limitations of the device (see https://github.com/freifunk-gluon/gluon/pull/2008) and an average price of 80€ we should list it in the recommend devices.
This PR introduces a new device category "small_kernel_part" and communities can decide if they want to list the device or not.

devices: add Linksys EA6350 (v3)

---

app.js

This loads the vendor list for the dropdown menu from the vendormodels
structure. This way, only vendors for enabled device categories are
displayed.

app: load vendors from vendormodels

---

index.html

This allows to quickly empty the search box. I think it is quite common to return to `/` on clicking something in the top left.

make router icon (top left) a reset button

---

app.js
config_template.js
devices.js

I adjusted the devices_info code to allow setting links per revision.
Probably not the nicest JavaScript code but I couldn't find any problems during my tests.
Fixes #79

app: allow device info links per revision

---

devices.js

To me it seems like naming the PI"1" image only PI could cause confusion. The name "PI" might suggest to some that this image works with the other PIs which aren't mentioned seperatly (currently PI1 and PI4).

devices: rename PI to PI1 for less confusion

---

devices.js

fritzfla.sh seems to be defunct, so switching to link provided by openwrt.

Change info link for Fritz! devices

---

app.js
devices.js

This adds support for the device AVM FRITZ!Box 3370 and the new image types which are needed for flashing via the EVA bootloader.

app/devices: add AVM FRITZ!Box 3370 v2

---

devices.js

I updated the devices.js to match all images available in the current Gluon master branch based on OpenWrt 21.02 split in 3 commits.
1. completely new devices
2. aliases for already existing devices but with changed image names
3. ignore x86-legacy .vdi and .vmdk images as I can't imagine any use case where they would be useful
Any concerns merging this into master?

devices: update devices for OpenWrt 21.02

---

pictures/tp-link-cpe510-v3.jpg

I forgot to add the symlink for `tp-link-cpe510-v3.jpg` 
Sorry for the additional work 😅

pictures: fixup #131 (symlink for cpe510-v3 was missing)

---

app.js

This fixes the broken URLs in Firefox. Tested with Firefox and Chromium.

app: replace unencoded plus signs (+) before decoding

---

devices.js

this supersedes #125 by having a nicer pictured installation info from Ingolstadt for the R6120 (and other devices)
adds installation instructions for
-  o2 box 6431
- Joy-IT OR750i
- Netgear DGN3500
- Netgear EX3700
- Netgear EX3800
- Netgear EX6150
- Netgear R6120
- Netgear R6220

add link to installation for some devices

---

devices.js

This commit adds a flash instruction link for the D-Link DAP-X1860 device.

Add D-Link DAP-X1860 flash instruction link

---

devices.js

The following devices were not added to the firmware-selector, while they are supported on gluon main:
* Cudy AP3000 Outdoor
* D-Link AQUILA PRO AI M60
* Extreme Networks WS-AP3915i
* FriendlyElec NanoPi R3S
* Sophos AP 15C
* Ubiquiti Unifi AC HD
* Ubiquiti Unifi nanoHD

devices: add various devices

---

app.css

This adds a dark mode for the firmware selector.

Add dark mode
